defmodule Test.StateChart.W3.Raise.Test144 do
  use SC.Case
  @tag :scxml_w3
  @tag conformance: "mandatory", spec: "raise"
  test "test144" do
    xml = """
    <?xml version="1.0" encoding="UTF-8"?>
    <ns0:scxml xmlns:ns0="http://www.w3.org/2005/07/scxml" initial="s0" version="1.0" datamodel="elixir">
        <ns0:state id="s0">
            <ns0:onentry>
                <ns0:raise event="foo" />
                <ns0:raise event="bar" />
            </ns0:onentry>
            <ns0:transition event="foo" target="s1" />
            <ns0:transition event="*" target="fail" />
        </ns0:state>
        <ns0:state id="s1">
            <ns0:transition event="bar" target="pass" />
            <ns0:transition event="*" target="fail" />
        </ns0:state>
        <ns0:final id="pass">
            <ns0:onentry>
                <ns0:log label="Outcome" expr="'pass'" />
            </ns0:onentry>
        </ns0:final>
        <ns0:final id="fail">
            <ns0:onentry>
                <ns0:log label="Outcome" expr="'fail'" />
            </ns0:onentry>
        </ns0:final>
    </ns0:scxml>
    """

    description =
      "The SCXML processor MUST place the event that is generated by the raise element at the rear of the session's internal event queue."

    test_scxml(xml, description, ["pass"], [])
  end
end
