defmodule SCXMLTest.Raise.Test144 do
  use Statifier.Case
  @tag :scxml_w3
  @tag required_features: [
         :basic_states,
         :event_transitions,
         :final_states,
         :log_elements,
         :onentry_actions,
         :raise_elements
       ]
  @tag conformance: "mandatory", spec: "raise"
  test "test144" do
    xml = """
    <?xml version="1.0" encoding="UTF-8"?>
    <scxml xmlns:ns0="http://www.w3.org/2005/07/scxml" initial="s0" version="1.0" datamodel="elixir">
        <state id="s0">
            <onentry>
                <raise event="foo" />
                <raise event="bar" />
            </onentry>
            <transition event="foo" target="s1" />
            <transition event="*" target="fail" />
        </state>
        <state id="s1">
            <transition event="bar" target="pass" />
            <transition event="*" target="fail" />
        </state>
        <final id="pass">
            <onentry>
                <log label="Outcome" expr="'pass'" />
            </onentry>
        </final>
        <final id="fail">
            <onentry>
                <log label="Outcome" expr="'fail'" />
            </onentry>
        </final>
    </scxml>
    """

    description =
      "The SCXML processor MUST place the event that is generated by the raise element at the rear of the session's internal event queue."

    test_scxml(xml, description, ["pass"], [])
  end
end
