name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - 'CLAUDE.md'
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - 'CLAUDE.md'
      - 'README.md'
      - 'docs/**'

jobs:
  lint-docs:
    name: Lint Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        globs: |
          **/*.md
          !node_modules/**/*.md

    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown-link-check-config.json'

  validate-memory:
    name: Validate Memory Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check CLAUDE.md structure
      run: |
        echo "Validating CLAUDE.md structure..."
        if ! grep -q "## Commands" CLAUDE.md; then
          echo "❌ CLAUDE.md missing Commands section"
          exit 1
        fi
        if ! grep -q "## Architecture" CLAUDE.md; then
          echo "❌ CLAUDE.md missing Architecture section"
          exit 1
        fi
        echo "✅ CLAUDE.md structure looks good"

    - name: Check README.md structure
      run: |
        echo "Validating README.md structure..."
        if ! grep -q "## Features" README.md; then
          echo "❌ README.md missing Features section"
          exit 1
        fi
        if ! grep -q "## Current Status" README.md; then
          echo "❌ README.md missing Current Status section"
          exit 1
        fi
        echo "✅ README.md structure looks good"

    - name: Validate documentation consistency
      run: |
        echo "Checking for API consistency between CLAUDE.md and README.md..."
        
        # Check that both files reference SC.Validator (not SC.Document.Validator)
        if grep -q "SC\.Document\.Validator" CLAUDE.md README.md; then
          echo "❌ Found outdated SC.Document.Validator references - should be SC.Validator"
          grep -n "SC\.Document\.Validator" CLAUDE.md README.md || true
          exit 1
        fi
        
        echo "✅ API references look consistent"